name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    #- uses: jakejarvis/s3-sync-action@master
    - name: copy to s3
      run: |
       rsync -hzvr . ubuntu@3.110.191.67:/home/ubuntu/server/
