name: Upload Website

on:
  push:
    branches:
    - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    #- uses: jakejarvis/s3-sync-action@master
    - name: copy to s3
      run: |
       echo "$RUNNER_NAME $RUNNER_OS"
       rsync -hzvr . ubuntu@3.110.191.67:/home/ubuntu/server/
       cat index.html > job_output.txt
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with: 
       name: html artifacts
       path: job_output.txt
